### ISSUE TITLE
Add emscripten-glfw to the bindings table

### ISSUE THREAD

**Issue by ypujante** [glfw/glfw.github.io#107]
Hello

I wanted to inquire if it would be possible to add emscripten-glfw in the Bindings table on the community page, something like

Language | Maintainer | Source
---------|--------|--------|
C++/Wasm | pongasoft | [emscripten-glfw](https://github.com/pongasoft/emscripten-glfw)

emscripten-glfw is a from scratch implementation of `glfw3.h` targeting the emscripten/browser platform (in this case, the [window is a canvas](https://github.com/pongasoft/emscripten-glfw/blob/master/docs/Usage.md#main-concept)). The implementation itself is in C++/JavaScript but of course it implements the C api (`glfw3.h`).

This implementation is free, open source (Apache 2.0) and hosted on [github](https://github.com/pongasoft/emscripten-glfw) and is an emscripten contrib port: this means that it can be used very simply when [compiling code](https://github.com/pongasoft/emscripten-glfw/tree/master?tab=readme-ov-file#using-emscripten-port), something like

```text
> emcc --use-port=contrib.glfw3 main.cpp -o build/index.html
```

There is a bunch of examples provided with the implementation, with the primary [test/demo](https://pongasoft.github.io/emscripten-glfw/test/demo/main.html) demonstrating (live in your browser) most of the features that are implemented, like full support for joystick, clipboard, 4k, etc...

This implementation is now fully available in ImGui since version 1.91.0 and as a real live application example, I wrote a [WebGPU Shade Toy](https://pongasoft.github.io/webgpu-shader-toy/) application (use Google Chrome for this one).

Thank you

**Comment by siavashserver** [comment]
Thanks!
