### ISSUE TITLE
PHP bindings 

### ISSUE THREAD

**Issue by mario-deluna** [glfw/glfw.github.io#93]
Hey there, i've created a PHP extension to support glfw:

Repo:
https://github.com/mario-deluna/php-glfw

Docs: 
https://phpgl.net/getting-started/window-creation.html

Example:
https://github.com/mario-deluna/php-glfw/blob/master/examples/01_triangle.php

Best regards 
Mario

**Comment by siavashserver** [comment]
Thank you!
