### ISSUE TITLE
Update Ruby bindings

### ISSUE THREAD

**Issue by ParadoxV5** [glfw/glfw.github.io#94]
Please replace the Ruby bindings listed to, or additionally include, [`vaiorabbit/ruby-opengl`](https://github.com/vaiorabbit/ruby-opengl).
Its bindings[^b] include both OpenGL and GLFW (and GLUT too).

[^b]: “wrappings” may be a more accurate term since it uses FFI rather than conventional porting.

The currently-listed [`nilium/ruby-glfw3`](https://github.com/nilium/ruby-glfw3) and its OpenGL companion [`nilium/opengl-core`](https://github.com/nilium/opengl-core) were archived and their last `master` branch commits were around 7 years ago.

**Comment by siavashserver** [comment]
Thank you!

**Comment by ParadoxV5** [comment]
👍
-----
@vaiorabbit Just noticed that I should also ping you when I opened this a month ago.
