### ISSUE TITLE
Update Odin bindings

### ISSUE THREAD

**Issue by flysand7** [glfw/glfw.github.io#98]
The bindings specified on website implement up to GLFW 3.2.1.

They were "merged" into Odin's [vendor](https://github.com/odin-lang/Odin/tree/master/vendor/glfw) collection starting August 2021, where they have been receiving a few improvements and bug fixes by the community, and updated at least until the version 3.3.8. I think the "official" version is the one that should be included on the website.

What follows is more of a personal request.

There's also a version of bindings written hosted on my [repository](https://github.com/flysand7/our/tree/main/packages/glfw3) (0BSD licensed), that is an alternative to the vendor version. Odin's rules for vendor collection specify that the naming convention for the bindings should match the original, to not confuse the users when searching the documentation. My bindings act more like easings that provide a slightly more Odin-adapted API and provide language-specific features that make using the library much more convenient and allow for much easier access to documentation via text editor features like LSP.

I'm planning to mantain my bindings at least for a few versions until a new major rolls out.

Also it's a weird place to put this comment, but writing these bindings I've found GLFW to be a really good quality API. The documentation is well thought-out, I loved it.

**Comment by siavashserver** [comment]
Thanks!
